name: bsf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.28.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter icons:
  andriod: true
  ios: true
  image-path: "assets/icons/dish.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/donut/donut_2.png
    - assets/images/donut/donut_3.png
    - assets/images/donut/donut_4.png
    - assets/images/donut/donut_5.png
    - assets/images/donut/donut_6.png
    - assets/images/donut/donut_7.png
    - assets/images/logo/donut2_logo.jpg
    - assets/images/logo/gladis_logo.jpg
    - assets/images/logo/leliuious_logo.jpg
    - assets/images/logo/lila_logo.png
    - assets/images/logo/monginis-logo.png
    - assets/images/logo/sweet-shop-logo.jpg
    - assets/images/logo/tasties_logo.jpg
    - assets/images/burger.png
    - assets/images/cloche.png
    - assets/images/delivery.png
    - assets/images/discount.png
    - assets/images/donut.png
    - assets/images/fast-delivery.png
    - assets/images/logo.png
    - assets/images/pizza-slice.png
    - assets/images/temp_donut.png
    - assets/images/temp_donat.jpg
    - assets/images/temp_vendor_bg.png
    - assets/images/temp_vendor_logo.png
    - assets/lottie/load.json
    - assets/icons/chat.png
    - assets/icons/dish.png
    - assets/icons/facebook.png
    - assets/icons/google-plus.png
    - assets/icons/login.png
    - assets/icons/signup.png
    - assets/icons/twitter.png
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/main_top.png
    - assets/images/signup_top.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
